name: Conditional

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Succeed
        run: |
          exit 0
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Succeed
        run: |
          echo "ok"
  run-if-failed:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: always() && (needs.job1.result == 'failure' || needs.job2.result == 'failure')
    steps:
      - name: Needs context
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          echo "$NEEDS_CONTEXT"
