name: pre

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  branch:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git push origin master:pre -f
